FROM armhf/alpine:latest

RUN apk add --no-cache git go musl-dev && mkdir /go
ENV GOPATH=/go
RUN go get -u github.com/prometheus/promu
COPY . /go/src/github.com/mitchellrj/hue_exporter
WORKDIR /go/src/github.com/mitchellrj/hue_exporter

VOLUME /build
CMD promu build && mv hue_exporter /build/hue_exporter.arm7.musl
