FROM armhf/alpine:latest

RUN apk add --no-cache git go musl-dev && mkdir /go
ENV GOPATH=/go
COPY . /go/src/github.com/mitchellrj/hue_exporter
WORKDIR /go/src/github.com/mitchellrj/hue_exporter

VOLUME /build
CMD go build -o /build/hue_exporter.arm7.musl
