apiVersion: apps/v1
kind: Deployment
metadata:
  name: hue-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: hue-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hue-exporter
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hue-exporter
    spec:
      containers:
        - name: hue-exporter
          image: mitchellrj/hue_exporter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9366
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /etc/hue_exporter/config.yml
              subPath: config.yml
      volumes:
        - name: config-volume
          configMap:
            name: hue-exporter-config
