apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: hue-exporter
    name: hue-exporter
  name: hue-exporter
  namespace: monitoring
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: hue-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: metrics
